# Generated by Django 5.2.14 on 2026-06-03 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Zakaz raqami')),
                ('status', models.CharField(choices=[('created', 'Yaratildi'), ('awaiting_payment', "Kassada to'lov kutilmoqda"), ('preparing', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('completed', 'Berildi'), ('cancelled', 'Bekor qilindi')], default='created', max_length=20, verbose_name='Holat')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('online', 'Online')], default='cash', max_length=10, verbose_name="To'lov turi")),
                ('payment_status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('paid', "To'langan")], default='unpaid', max_length=10, verbose_name="To'lov holati")),
                ('customer_note', models.TextField(blank=True, verbose_name='Mijoz izohi')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jami')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.table', verbose_name='Stol')),
            ],
            options={
                'verbose_name': 'Zakaz',
                'verbose_name_plural': 'Zakazlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi (snapshot)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx (snapshot)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jami (snapshot)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem', verbose_name='Taom')),
                ('modifiers', models.ManyToManyField(blank=True, to='menu.modifier', verbose_name='Variantlar')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Zakaz')),
            ],
            options={
                'verbose_name': 'Zakaz tarkibi',
                'verbose_name_plural': 'Zakaz tarkibi',
            },
        ),
    ]
