# Generated by Django 5.2.14 on 2026-06-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('click_trans_id', models.CharField(db_index=True, max_length=64, verbose_name='Click tranzaksiya ID')),
                ('click_paydoc_id', models.CharField(blank=True, max_length=64, verbose_name='Click hujjat ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Summa (so'm)")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('prepared', 'Tayyorlandi'), ('confirmed', 'Tasdiqlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=12, verbose_name='Holat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_transactions', to='orders.order', verbose_name='Zakaz')),
            ],
            options={
                'verbose_name': 'Click tranzaksiyasi',
                'verbose_name_plural': 'Click tranzaksiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('transaction_id', models.CharField(max_length=64, unique=True, verbose_name='Payme tranzaksiya ID')),
                ('amount', models.BigIntegerField(verbose_name='Summa (tiyin)')),
                ('state', models.IntegerField(choices=[(1, 'Yaratildi'), (2, 'Yakunlandi'), (-1, 'Bekor (yaratilgan)'), (-2, 'Bekor (yakunlangan)')], default=1, verbose_name='Holat')),
                ('reason', models.IntegerField(blank=True, null=True, verbose_name='Bekor sababi')),
                ('create_time', models.BigIntegerField(default=0, verbose_name='Yaratilgan vaqt (ms)')),
                ('perform_time', models.BigIntegerField(default=0, verbose_name='Yakunlangan vaqt (ms)')),
                ('cancel_time', models.BigIntegerField(default=0, verbose_name='Bekor vaqti (ms)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payme_transactions', to='orders.order', verbose_name='Zakaz')),
            ],
            options={
                'verbose_name': 'Payme tranzaksiyasi',
                'verbose_name_plural': 'Payme tranzaksiyalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
