# Generated by Django 5.2.14 on 2026-06-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('endpoint', models.TextField(verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='p256dh kalit')),
                ('auth', models.CharField(max_length=255, verbose_name='auth kalit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='orders.order', verbose_name='Zakaz')),
            ],
            options={
                'verbose_name': 'Push obuna',
                'verbose_name_plural': 'Push obunalar',
            },
        ),
    ]
